name: build-and-deploy

#   if: ${{ github.event_name == 'push' }}

on:
  pull_request:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Build site
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build
      - name: Deploy site
        if: ${{ success() && github.event_name == 'push' }}
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
